[build]
  publish = "."
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/explorer.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/explorer.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

