(() => {
'use strict';
const CFG=[['Centrales','green'],['Detectores','amber'],['Accesorios inalámbricos','blue'],['Cámaras IP','violet'],['NVRs Profesionales','rose'],['Accesorios CCTV','cyan','Soportes']];
const $=id=>document.getElementById(id), fmt=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stock(v){let s=String(v??'').toLowerCase();if(/sin stock|agotado|none|out/.test(s))return['is-out','Sin stock'];if(/limit|bajo|low|poco/.test(s))return['is-low','Stock limitado'];return['is-ok','Disponible'];}
function render(){const api=window.HX_EXPLORER_PRO,root=$('quickAddContent');if(!root)return;if(!api?.quickData){root.innerHTML='<p class="quick-add-empty">Cargando productos…</p>';return;}root.innerHTML=CFG.map(([name,tone,label])=>{const f=api.quickData([name])[0];if(!f)return'';const cards=f.products.slice(0,6).map(p=>{const st=stock(p.stock),img=p.image?`<img src="${esc(p.image)}" alt="" loading="lazy">`:'';return `<article class="quick-add-product" data-ref="${esc(p.reference)}" data-price="${p.price}"><div class="quick-add-photo">${img}</div><div class="quick-add-main"><strong>${esc(p.reference)}</strong><span>${esc(p.description)}</span><small class="${st[0]}"><i></i>${st[1]}</small></div><div class="quick-add-buy"><b>${fmt.format(p.price)}</b><div class="quick-add-qty"><button data-minus>−</button><span>1</span><button data-plus>+</button></div><button class="quick-add-do" data-add>Añadir</button></div></article>`}).join('');return `<section class="quick-add-section tone-${tone}"><h3>${esc(label||f.family)}</h3><div class="quick-add-products">${cards}</div></section>`}).join('');}
function open(){const m=$('quickAddModal');if(!m)return;render();m.classList.remove('hidden');m.setAttribute('aria-hidden','false');}
function close(){const m=$('quickAddModal');if(!m)return;m.classList.add('hidden');m.setAttribute('aria-hidden','true');}
function install(){$('btnQuickAdd')?.addEventListener('click',open);$('quickAddModal')?.addEventListener('click',e=>{if(e.target.closest('[data-quick-add-close]'))return close();const c=e.target.closest('.quick-add-product');if(!c)return;const q=c.querySelector('.quick-add-qty span');let n=Math.max(1,Number(q?.textContent)||1);if(e.target.closest('[data-minus]')){n=Math.max(1,n-1);q.textContent=n;return}if(e.target.closest('[data-plus]')){q.textContent=n+1;return}if(e.target.closest('[data-add]')){const ok=window.hxAddProductoSeguro?.(c.dataset.ref,n,null,Number(c.dataset.price));if(ok){try{window.render?.()}catch(_){}const b=e.target.closest('[data-add]');b.textContent='Añadido';setTimeout(()=>b.textContent='Añadir',800)}}});addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('quickAddModal')?.classList.contains('hidden'))close()});addEventListener('hx:catalogo-cargado',()=>{if(!$('quickAddModal')?.classList.contains('hidden'))render()});}
window.HX_QUICK_ADD={open,close,render};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();